{ palette }:

let
  inherit (palette) ui bufferHighlight bufferText explorerGit syntax;
in
{
  vim.highlight = {
    Normal = { bg = "NONE"; fg = ui.text; };
    # Keep inactive splits readable; borders and cursorline communicate focus
    # without dimming an entire buffer to comment-level contrast.
    NormalNC = { bg = "NONE"; fg = ui.text; };
    NormalFloat = { bg = ui.surface; fg = ui.text; };
    FloatBorder = { bg = ui.surface; fg = ui.border; };
    FloatTitle = { bg = ui.surface; fg = ui.bright; bold = true; };
    FloatFooter = { bg = ui.surface; fg = ui.muted; italic = true; };
    FloatShadow = { bg = ui.bg; blend = 55; };
    Directory = { fg = ui.accent; bold = true; };
    Title = { fg = ui.bright; bold = true; };
    Question.fg = ui.info;
    Conceal.fg = ui.muted;
    SignColumn.bg = "NONE";
    CursorLine.bg = ui.raised;
    CursorLineNr = { bg = ui.raised; fg = ui.accent; bold = true; };
    LineNr = { bg = "NONE"; fg = ui.border; };
    Visual = { bg = ui.selected; fg = ui.bright; };
    Search = { bg = bufferHighlight.search; fg = ui.bright; bold = true; };
    IncSearch = { bg = ui.warning; fg = ui.bg; bold = true; };
    CurSearch = { bg = ui.accent; fg = ui.bg; bold = true; underline = true; };
    Substitute = { bg = ui.danger; fg = ui.bg; bold = true; };
    MatchParen = { bg = ui.selected; fg = ui.warning; bold = true; underline = true; };
    Pmenu = { bg = ui.surface; fg = ui.text; };
    PmenuSel = { bg = ui.selected; fg = ui.bright; bold = true; };
    PmenuExtra = { bg = ui.surface; fg = ui.muted; };
    PmenuKind = { bg = ui.surface; fg = ui.accent; };
    PmenuMatch = { fg = ui.accent; bold = true; };
    PmenuMatchSel = { bg = ui.selected; fg = ui.warning; bold = true; };
    PmenuSbar.bg = ui.surface;
    PmenuThumb.bg = ui.border;
    WildMenu = { bg = ui.selected; fg = ui.bright; bold = true; };
    QuickFixLine = { bg = ui.hover; fg = ui.bright; bold = true; };
    Folded = { bg = ui.surface; fg = ui.muted; };
    FoldColumn = { bg = "NONE"; fg = ui.border; };
    ColorColumn.bg = ui.surface;
    NonText.fg = ui.border;
    SpecialKey.fg = ui.border;
    Whitespace.fg = ui.border;
    EndOfBuffer.fg = ui.bg;
    WinSeparator = { bg = "NONE"; fg = ui.border; };
    StatusLine = { bg = ui.surface; fg = ui.text; };
    StatusLineNC = { bg = ui.bg; fg = ui.border; };
    WinBar = { bg = "NONE"; fg = ui.text; bold = true; };
    WinBarNC = { bg = "NONE"; fg = ui.muted; };
    TabLine = { bg = ui.surface; fg = ui.muted; };
    TabLineFill.bg = ui.bg;
    TabLineSel = { bg = ui.selected; fg = ui.bright; bold = true; };
    MsgArea.fg = ui.text;
    ModeMsg = { fg = ui.accent; bold = true; };
    MoreMsg.fg = ui.info;
    ErrorMsg = { fg = ui.danger; bold = true; };
    WarningMsg.fg = ui.warning;
    Error = { fg = ui.danger; bold = true; };
    Underlined = { fg = ui.info; underline = true; };
    SpellBad = { undercurl = true; sp = ui.danger; };
    SpellCap = { undercurl = true; sp = ui.warning; };
    SpellLocal = { undercurl = true; sp = ui.info; };
    SpellRare = { undercurl = true; sp = ui.violet; };

    # Vim syntax groups provide a consistent fallback for filetypes without
    # a Treesitter parser and are also the link targets for semantic groups.
    Comment = { fg = syntax.comment; italic = true; };
    Constant.fg = syntax.constant;
    String.fg = syntax.string;
    Character.fg = syntax.string;
    Number.fg = syntax.number;
    Boolean = { fg = syntax.constant; bold = true; };
    Float.fg = syntax.number;
    Identifier.fg = syntax.variable;
    Function = { fg = syntax.function; bold = true; };
    Statement = { fg = syntax.keyword; bold = true; };
    Conditional.fg = syntax.keyword;
    Repeat.fg = syntax.keyword;
    Label.fg = syntax.markup;
    Operator.fg = syntax.operator;
    Keyword = { fg = syntax.keyword; bold = true; };
    Exception = { fg = syntax.keyword; bold = true; };
    PreProc.fg = syntax.markup;
    Include.fg = syntax.markup;
    Define.fg = syntax.markup;
    Macro = { fg = syntax.markup; bold = true; };
    Type.fg = syntax.type;
    StorageClass = { fg = syntax.keyword; italic = true; };
    Structure.fg = syntax.struct;
    Typedef.fg = syntax.type;
    Special.fg = syntax.operator;
    SpecialChar.fg = syntax.operator;
    Tag.fg = syntax.markup;
    Delimiter.fg = syntax.punctuation;
    Todo = { bg = ui.hover; fg = syntax.constant; bold = true; };

    # Treesitter captures carry the structural distinctions that the base16
    # theme flattens, especially calls vs definitions and fields vs locals.
    "@comment" = { link = "Comment"; };
    "@comment.documentation" = { fg = syntax.comment; italic = true; };
    "@constant" = { link = "Constant"; };
    "@constant.builtin" = { fg = syntax.constant; bold = true; };
    "@constant.macro" = { link = "Macro"; };
    "@string" = { link = "String"; };
    "@string.documentation" = { fg = syntax.string; italic = true; };
    "@string.escape" = { fg = syntax.operator; bold = true; };
    "@string.regexp" = { fg = syntax.operator; };
    "@string.special" = { fg = syntax.constant; };
    "@string.special.path" = { fg = syntax.string; underline = true; };
    "@string.special.symbol" = { fg = syntax.constant; };
    "@string.special.url" = { fg = syntax.operator; underline = true; };
    "@character" = { link = "Character"; };
    "@character.special" = { fg = syntax.operator; };
    "@number" = { link = "Number"; };
    "@number.float" = { link = "Float"; };
    "@boolean" = { link = "Boolean"; };
    "@variable" = { fg = syntax.variable; };
    "@variable.builtin" = { fg = syntax.constant; italic = true; };
    "@variable.parameter" = { fg = syntax.parameter; italic = true; };
    "@variable.parameter.builtin" = { fg = syntax.constant; italic = true; };
    "@variable.member" = { fg = syntax.property; };
    "@property" = { fg = syntax.property; };
    "@function" = { link = "Function"; };
    "@function.builtin" = { fg = syntax.function; italic = true; };
    "@function.call" = { fg = syntax.function; };
    "@function.macro" = { link = "Macro"; };
    "@function.method" = { fg = syntax.function; bold = true; };
    "@function.method.call" = { fg = syntax.function; };
    "@constructor" = { fg = syntax.class; bold = true; };
    "@type" = { link = "Type"; };
    "@type.builtin" = { fg = syntax.type; italic = true; };
    "@type.definition" = { fg = syntax.type; bold = true; };
    "@type.qualifier" = { fg = syntax.keyword; italic = true; };
    "@module" = { fg = syntax.namespace; };
    "@module.builtin" = { fg = syntax.namespace; italic = true; };
    "@attribute" = { fg = syntax.markup; italic = true; };
    "@attribute.builtin" = { fg = syntax.markup; };
    "@keyword" = { link = "Keyword"; };
    "@keyword.coroutine" = { fg = syntax.keyword; bold = true; };
    "@keyword.conditional" = { fg = syntax.keyword; };
    "@keyword.repeat" = { fg = syntax.keyword; };
    "@keyword.exception" = { fg = syntax.keyword; };
    "@keyword.function" = { fg = syntax.keyword; bold = true; };
    "@keyword.operator" = { fg = syntax.operator; };
    "@keyword.return" = { fg = syntax.keyword; bold = true; };
    "@keyword.import" = { fg = syntax.markup; bold = true; };
    "@keyword.type" = { fg = syntax.keyword; };
    "@keyword.modifier" = { fg = syntax.keyword; italic = true; };
    "@keyword.debug" = { fg = ui.warning; };
    "@keyword.directive" = { fg = syntax.markup; };
    "@keyword.directive.define" = { fg = syntax.markup; italic = true; };
    "@label" = { link = "Label"; };
    "@operator" = { link = "Operator"; };
    "@punctuation.delimiter" = { link = "Delimiter"; };
    "@punctuation.bracket" = { fg = syntax.punctuation; };
    "@punctuation.special" = { fg = syntax.operator; };
    "@punctuation.special.markdown" = { fg = syntax.markup; };
    "@tag" = { fg = syntax.markup; bold = true; };
    "@tag.attribute" = { fg = syntax.property; italic = true; };
    "@tag.delimiter" = { fg = syntax.punctuation; };
    "@markup.heading" = { fg = syntax.function; bold = true; };
    "@markup.strong" = { fg = bufferText.strong; bold = true; };
    "@markup.italic" = { fg = ui.text; italic = true; };
    "@markup.strikethrough" = { fg = ui.muted; strikethrough = true; };
    "@markup.link" = { fg = syntax.operator; underline = true; };
    "@markup.link.label" = { fg = syntax.markup; };
    "@markup.link.url" = { fg = syntax.operator; underline = true; };
    "@markup.raw" = { fg = syntax.string; };
    "@markup.list" = { fg = syntax.markup; bold = true; };
    "@markup.quote" = { fg = syntax.comment; italic = true; };
    "@comment.error" = { fg = ui.danger; bold = true; };
    "@comment.warning" = { fg = ui.warning; bold = true; };
    "@comment.todo" = { fg = syntax.constant; bold = true; };
    "@comment.note" = { fg = ui.info; bold = true; };
    "@diff.plus" = { fg = ui.success; };
    "@diff.minus" = { fg = ui.danger; };
    "@diff.delta" = { fg = ui.warning; };

    # LSP semantic tokens take precedence over Treesitter when a server
    # supplies them, so mirror the same roles instead of accepting defaults.
    "@lsp.type.namespace" = { fg = syntax.namespace; };
    "@lsp.type.module" = { fg = syntax.namespace; };
    "@lsp.type.type" = { link = "Type"; };
    "@lsp.type.class" = { fg = syntax.class; };
    "@lsp.type.enum" = { fg = syntax.enum; };
    "@lsp.type.interface" = { fg = syntax.interface; };
    "@lsp.type.struct" = { fg = syntax.struct; };
    "@lsp.type.typeParameter" = { fg = syntax.typeParameter; italic = true; };
    "@lsp.type.parameter" = { fg = syntax.parameter; italic = true; };
    "@lsp.type.variable" = { fg = syntax.variable; };
    "@lsp.type.property" = { fg = syntax.property; };
    "@lsp.type.enumMember" = { fg = syntax.constant; };
    "@lsp.type.function" = { link = "Function"; };
    "@lsp.type.method" = { fg = syntax.function; };
    "@lsp.type.macro" = { link = "Macro"; };
    "@lsp.type.keyword" = { link = "Keyword"; };
    "@lsp.type.comment" = { link = "Comment"; };
    "@lsp.type.string" = { link = "String"; };
    "@lsp.type.number" = { link = "Number"; };
    "@lsp.type.regexp" = { fg = syntax.operator; };
    "@lsp.type.operator" = { link = "Operator"; };
    "@lsp.type.decorator" = { fg = syntax.markup; italic = true; };
    "@lsp.type.event" = { fg = syntax.constant; };
    "@lsp.type.label" = { link = "Label"; };
    # Common language-server extensions (notably rust-analyzer) retain the
    # same semantic vocabulary instead of falling back to editor defaults.
    "@lsp.type.builtinType" = { fg = syntax.type; italic = true; };
    "@lsp.type.typeAlias" = { fg = syntax.type; };
    "@lsp.type.union" = { fg = syntax.struct; };
    "@lsp.type.generic" = { fg = syntax.typeParameter; italic = true; };
    "@lsp.type.lifetime" = { fg = syntax.parameter; italic = true; };
    "@lsp.type.selfKeyword" = { fg = syntax.constant; italic = true; };
    "@lsp.type.boolean" = { link = "Boolean"; };
    "@lsp.type.escapeSequence" = { fg = syntax.operator; bold = true; };
    "@lsp.type.formatSpecifier" = { fg = syntax.operator; };
    "@lsp.type.punctuation" = { fg = syntax.punctuation; };
    "@lsp.mod.deprecated" = { strikethrough = true; };
    "@lsp.mod.readonly" = { fg = syntax.constant; };
    "@lsp.mod.defaultLibrary" = { italic = true; };
    "@lsp.mod.documentation" = { italic = true; };

    DiagnosticError = { fg = ui.danger; bold = true; };
    DiagnosticWarn = { fg = ui.warning; bold = true; };
    DiagnosticInfo.fg = ui.info;
    DiagnosticHint.fg = ui.violet;
    DiagnosticOk.fg = ui.success;
    DiagnosticSignError = { fg = ui.danger; bold = true; };
    DiagnosticSignWarn = { fg = ui.warning; bold = true; };
    DiagnosticSignInfo = { fg = ui.info; bold = true; };
    DiagnosticSignHint = { fg = ui.violet; bold = true; };
    DiagnosticSignOk = { fg = ui.success; bold = true; };
    DiagnosticVirtualTextError = { bg = bufferHighlight.error; fg = ui.danger; };
    DiagnosticVirtualTextWarn = { bg = bufferHighlight.warning; fg = ui.warning; };
    DiagnosticVirtualTextInfo = { bg = bufferHighlight.info; fg = ui.info; };
    DiagnosticVirtualTextHint = { bg = bufferHighlight.hint; fg = ui.violet; };
    DiagnosticVirtualTextOk = { bg = bufferHighlight.ok; fg = ui.success; };
    DiagnosticFloatingError.fg = ui.danger;
    DiagnosticFloatingWarn.fg = ui.warning;
    DiagnosticFloatingInfo.fg = ui.info;
    DiagnosticFloatingHint.fg = ui.violet;
    DiagnosticFloatingOk.fg = ui.success;
    DiagnosticUnderlineError = { undercurl = true; sp = ui.danger; };
    DiagnosticUnderlineWarn = { undercurl = true; sp = ui.warning; };
    DiagnosticUnderlineInfo = { undercurl = true; sp = ui.info; };
    DiagnosticUnderlineHint = { undercurl = true; sp = ui.violet; };
    DiagnosticUnderlineOk = { undercurl = true; sp = ui.success; };
    DiagnosticDeprecated = { fg = ui.muted; strikethrough = true; };
    DiagnosticUnnecessary.fg = ui.muted;

    LspReferenceText.bg = ui.raised;
    LspReferenceRead = { bg = ui.raised; underline = true; };
    LspReferenceWrite = { bg = ui.selected; bold = true; underline = true; };
    LspSignatureActiveParameter = { fg = ui.accent; bold = true; underline = true; };
    LspInlayHint = { bg = ui.raised; fg = ui.muted; italic = true; };
    LspCodeLens = { fg = ui.muted; italic = true; };
    LspCodeLensSeparator.fg = ui.border;

    DiffAdd = { bg = bufferHighlight.diffAdd; fg = explorerGit.added; };
    DiffChange = { bg = bufferHighlight.diffChange; fg = explorerGit.modified; };
    DiffDelete = { bg = bufferHighlight.diffDelete; fg = explorerGit.deleted; };
    DiffText = { bg = bufferHighlight.diffText; fg = ui.bright; bold = true; };
    Added.fg = explorerGit.added;
    Changed.fg = explorerGit.modified;
    Removed.fg = explorerGit.deleted;
    GitSignsAdd.fg = explorerGit.added;
    GitSignsChange.fg = explorerGit.modified;
    GitSignsDelete.fg = explorerGit.deleted;
    GitSignsUntracked.fg = explorerGit.untracked;

    BlinkCmpMenu = { bg = ui.surface; fg = ui.text; };
    BlinkCmpMenuBorder = { bg = ui.surface; fg = ui.border; };
    BlinkCmpMenuSelection = { bg = ui.selected; fg = ui.bright; bold = true; };
    BlinkCmpLabel.fg = ui.text;
    BlinkCmpLabelMatch = { fg = ui.accent; bold = true; };
    BlinkCmpLabelDetail.fg = ui.muted;
    BlinkCmpLabelDescription.fg = ui.muted;
    BlinkCmpSource.fg = ui.muted;
    BlinkCmpKind.fg = ui.accent;
    BlinkCmpKindFunction.fg = ui.accent;
    BlinkCmpKindMethod.fg = ui.accent;
    BlinkCmpKindConstructor.fg = ui.violet;
    BlinkCmpKindClass.fg = ui.violet;
    BlinkCmpKindInterface.fg = ui.info;
    BlinkCmpKindStruct.fg = ui.violet;
    BlinkCmpKindEnum.fg = ui.warning;
    BlinkCmpKindEnumMember.fg = ui.warning;
    BlinkCmpKindModule.fg = ui.info;
    BlinkCmpKindTypeParameter.fg = ui.violet;
    BlinkCmpKindVariable.fg = ui.text;
    BlinkCmpKindField.fg = ui.info;
    BlinkCmpKindProperty.fg = ui.info;
    BlinkCmpKindConstant.fg = ui.warning;
    BlinkCmpKindText.fg = ui.success;
    BlinkCmpKindString.fg = ui.success;
    BlinkCmpKindKeyword.fg = ui.danger;
    BlinkCmpKindOperator.fg = ui.info;
    BlinkCmpKindSnippet.fg = ui.violet;
    BlinkCmpScrollBarGutter.bg = ui.surface;
    BlinkCmpScrollBarThumb.bg = ui.border;
    BlinkCmpDoc = { bg = ui.surface; fg = ui.text; };
    BlinkCmpDocBorder = { bg = ui.surface; fg = ui.border; };
    BlinkCmpDocSeparator = { bg = ui.surface; fg = ui.border; };
    BlinkCmpDocCursorLine.bg = ui.hover;
    BlinkCmpSignatureHelp = { bg = ui.surface; fg = ui.text; };
    BlinkCmpSignatureHelpBorder = { bg = ui.surface; fg = ui.border; };
    BlinkCmpSignatureHelpActiveParameter = { fg = ui.accent; bold = true; };

    WhichKeyNormal = { bg = ui.surface; fg = ui.text; };
    WhichKeyBorder = { bg = ui.surface; fg = ui.border; };
    WhichKeyTitle = { bg = ui.surface; fg = ui.bright; bold = true; };
    WhichKey = { fg = ui.accent; bold = true; };
    WhichKeyGroup = { fg = ui.violet; bold = true; };
    WhichKeyDesc.fg = ui.text;
    WhichKeySeparator.fg = ui.border;
    WhichKeyValue.fg = ui.muted;
    WhichKeyIcon.fg = ui.accent;
    WhichKeyIconAzure.fg = ui.info;
    WhichKeyIconBlue.fg = ui.info;
    WhichKeyIconCyan.fg = ui.accent;
    WhichKeyIconGreen.fg = ui.success;
    WhichKeyIconGrey.fg = ui.muted;
    WhichKeyIconOrange.fg = ui.warning;
    WhichKeyIconPurple.fg = ui.violet;
    WhichKeyIconRed.fg = ui.danger;
    WhichKeyIconYellow.fg = ui.warning;
    DevIconDefault.fg = ui.accent;

    SnacksTerminal = { bg = ui.surface; fg = ui.text; };
    SnacksTerminalBorder = { bg = ui.surface; fg = ui.border; };
    SnacksTerminalTitle = { bg = ui.surface; fg = ui.bright; bold = true; };
    SnacksInputNormal = { bg = ui.surface; fg = ui.text; };
    SnacksInputBorder = { bg = ui.surface; fg = ui.border; };
    SnacksInputTitle = { bg = ui.surface; fg = ui.bright; bold = true; };
    SnacksInputIcon.fg = ui.accent;
    SnacksIndent.fg = ui.border;
    SnacksIndentScope.fg = ui.accent;
    SnacksPickerNormal = { bg = ui.surface; fg = ui.text; };
    SnacksPickerBox = { bg = ui.surface; fg = ui.text; };
    SnacksPickerBorder = { bg = ui.surface; fg = ui.border; };
    SnacksPickerTitle = { bg = ui.surface; fg = ui.bright; bold = true; };
    SnacksPickerInput = { bg = ui.surface; fg = ui.text; };
    SnacksPickerInputBorder = { bg = ui.surface; fg = ui.border; };
    SnacksPickerInputTitle = { bg = ui.surface; fg = ui.bright; bold = true; };
    SnacksPickerInputSearch = { fg = ui.accent; bold = true; };
    SnacksPickerList = { bg = ui.surface; fg = ui.text; };
    SnacksPickerListCursorLine = { bg = ui.selected; fg = ui.bright; bold = true; };
    SnacksPickerPreview = { bg = ui.surface; fg = ui.text; };
    SnacksPickerPreviewCursorLine.bg = ui.hover;
    SnacksPickerMatch = { fg = ui.accent; bold = true; };
    SnacksPickerSearch = { bg = ui.hover; fg = ui.bright; bold = true; };
    SnacksPickerPrompt.fg = ui.accent;
    SnacksPickerTotals.fg = ui.muted;
    SnacksPickerSelected = { fg = ui.bright; bold = true; };
    SnacksPickerUnselected.fg = ui.border;
    SnacksPickerFile.fg = ui.text;
    SnacksPickerDirectory = { fg = ui.info; bold = true; };
    SnacksPickerDir.fg = ui.muted;
    SnacksPickerPathHidden.fg = ui.text;
    SnacksPickerPathIgnored = { fg = ui.muted; italic = true; };
    SnacksPickerTree.fg = ui.border;
    SnacksPickerDimmed.fg = ui.muted;
    SnacksPickerComment.fg = ui.muted;
    SnacksPickerDesc.fg = ui.muted;
    SnacksPickerDelim.fg = ui.border;
    SnacksPickerToggle.fg = ui.info;
    SnacksPickerSpinner.fg = ui.accent;
    SnacksPickerCmd.fg = ui.violet;
    SnacksPickerSpecial.fg = ui.accent;
    SnacksPickerIdx.fg = ui.muted;
    SnacksPickerRow.fg = ui.muted;
    SnacksPickerCol.fg = ui.muted;
    SnacksPickerGitBranch.fg = ui.violet;
    SnacksPickerGitStatus = { fg = ui.bright; bold = true; };
    SnacksPickerGitStatusAdded = { fg = explorerGit.added; bold = true; };
    SnacksPickerGitStatusModified = { fg = explorerGit.modified; bold = true; };
    SnacksPickerGitStatusDeleted = { fg = explorerGit.deleted; bold = true; };
    SnacksPickerGitStatusUntracked = { fg = explorerGit.untracked; bold = true; };
    SnacksPickerGitStatusIgnored = { fg = ui.muted; italic = true; };
    SnacksPickerGitStatusStaged = { fg = explorerGit.staged; bold = true; };
    SnacksPickerGitStatusRenamed = { fg = explorerGit.renamed; bold = true; };
    SnacksPickerGitStatusCopied = { fg = explorerGit.renamed; bold = true; };
    SnacksPickerGitStatusUnmerged = { fg = explorerGit.deleted; bold = true; underline = true; };
    SnacksPickerIcon.fg = ui.accent;
    SnacksPickerIconFile.fg = ui.text;
    SnacksPickerIconFunction.fg = ui.accent;
    SnacksPickerIconMethod.fg = ui.accent;
    SnacksPickerIconClass.fg = ui.violet;
    SnacksPickerIconInterface.fg = ui.info;
    SnacksPickerIconStruct.fg = ui.violet;
    SnacksPickerIconModule.fg = ui.info;
    SnacksPickerIconString.fg = ui.success;
    SnacksPickerIconKeyword.fg = ui.danger;
    SnacksPickerIconOperator.fg = ui.info;
    SnacksDashboardNormal = { bg = "NONE"; fg = ui.text; };
    SnacksDashboardHeader.fg = ui.accent;
    SnacksDashboardKey.fg = ui.violet;
    SnacksDashboardIcon.fg = ui.info;
    SnacksDashboardDesc.fg = ui.text;
    SnacksDashboardDir.fg = ui.muted;
    SnacksDashboardFooter.fg = ui.muted;
  };
}
